### ISSUE TITLE
why i curl the course url，the html is empty？i had used the right cookie

### ISSUE THREAD

**Issue by lqyq** [weilu/towardmit#9] opened 2022-06-10 05:21 UTC

**Comment by weilu** [comment] 2022-06-10 14:02
It's possible the course content html pages have changed since I wrote the script. I don't have access to the courses anymore. You may need to look into the page HTML source and debug this and update the script.

**Comment by weilu** [comment] 2022-06-10 14:03
Closing as this is a duplicate of #8

**Closed as completed by weilu** 2022-06-10 14:03 UTC
